import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Sidebar from "./components/Sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="flex flex-row justify-center"
      >
        <div className="basis-1/5">
        <nav>
          <ul>
            <li><Link href="/alltasks">All Tasks</Link></li>
          </ul>
        </nav>
        {/* <Sidebar/> */}
        </div>

        
        <main className="basis-1/2">
        {children}
        </main>
        
      </body>
    </html>
  );
}
